[package]
name = "dojo_erc"
version = "0.3.1"
cairo-version = "2.1.0"
version-The-marquis-erc20 = "0.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo",tag="v0.3.1" }


[[target.dojo]]
build-external-contracts = [ 
    "dojo_erc::erc20_models::*"
]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
#world = "0x5ac3d4b630c01b2e349f0f6266528e4a2e01ab5c07253cf5ecfc790cffe8a7f"

# keystore_password = "password"
# keystore_path = "../keystore.json"
