[package]
cairo-version = "2.4.0"
name = "l2_v4_2"
version = "0.5.1"
version-The-marquis = "0.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", version = "0.5.1" }
#starknet = ">=2.2.0"

[[target.dojo]]
build-external-contracts = ["dojo_erc::erc20_contract::*"]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
# rpc_url = "https://starknet-goerli.infura.io/v3/c45bd0ce3e584ba4a5e6a5928c9c0b0f"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"

# rpc_url = "https://starknet-goerli.infura.io/v3/c45bd0ce3e584ba4a5e6a5928c9c0b0f"
# account_address = "0x03cff41d65a796886f6496684c7130dc661b42f2ef049adec6c397a8e4b99fa6"
# private_key = "0x05adb3f31ba50d873dc6c93585d7e392b0b872860cefe69943ca6f7afce0a319"
